_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: ""
  MASK_ON: False
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
  ROI_HEADS:
    NUM_CLASSES: 2
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.02
  STEPS: (4000, 4200)
  MAX_ITER: 4500
INPUT:
  MAX_SIZE_TRAIN: 256
  MIN_SIZE_TRAIN: (0, 256)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TEST: 256
  MIN_SIZE_TEST: 0