_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: ""
  MASK_ON: False
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
  ROI_HEADS:
    NUM_CLASSES: 2
    SCORE_THRESH_TEST: 0.8
    NMS_THRESH_TEST: 0.25
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0002
  STEPS: (40000, 42000)
  MAX_ITER: 45000
INPUT:
  MAX_SIZE_TRAIN: 256
  MIN_SIZE_TRAIN: (0, 256)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TEST: 1280
  MIN_SIZE_TEST: 0
  RANDOM_FLIP: "none"